// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(CinemaDbContext))]
    [Migration("20231204204250_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("GeneroId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Generos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Accion"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Aventura"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Ciencia Ficcion"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedia"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Documental"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Drama"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Fantasia"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Musical"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Suspenso"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Terror"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PeliculaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("Genre")
                        .HasColumnType("int")
                        .HasColumnName("Genero");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Poster");

                    b.Property<string>("Synopsis")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Sonopsis");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Titulo");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Genre");

                    b.ToTable("Peliculas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Genre = 9,
                            PosterUrl = "https://th.bing.com/th/id/OIP.PwZP-r6lwxa7jqI9VHU7cwAAAA?w=123&h=180&c=7&r=0&o=5&pid=1.7",
                            Synopsis = "Hércules Poirot asiste a regañadientes a una sesión de espiritismo. Cuando uno de los invitados es asesinado, el detective se ve inmerso en un siniestro mundo de sombras y secretos.",
                            Title = "Caceria en Venecia",
                            Trailer = "https://www.youtube.com/watch?v=JymKmSe5TOk&ab_channel=20thCenturyStudiosLA"
                        },
                        new
                        {
                            Id = 2,
                            Genre = 7,
                            PosterUrl = "https://th.bing.com/th/id/OIP.sI0vbZwcYD1oEHt04j1vQwAAAA?w=115&h=180&c=7&r=0&o=5&pid=1.7",
                            Synopsis = "Cuando Shrek y la princesa Fiona regresan de su luna de miel, los padres de ella los invitan a visitar el reino de Muy Muy Lejano para celebrar la boda. Para Shrek, al que nunca abandona su fiel amigo Asno, esto constituye un gran problema.",
                            Title = "Shrek 2",
                            Trailer = "https://www.youtube.com/watch?v=xBxVgh-kgAI&ab_channel=JoyasDeLaAnimaci%C3%B3n"
                        },
                        new
                        {
                            Id = 3,
                            Genre = 10,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/ComingSoon/200x285/988.jpg?v=00002177",
                            Synopsis = "Un niño que escucha voces en su cabeza decide liberarlas contra sus abusivos padres.",
                            Title = "Toc toc toc",
                            Trailer = "https://www.youtube.com/watch?v=K27WSoKbP_A&ab_channel=BFDistribution"
                        },
                        new
                        {
                            Id = 4,
                            Genre = 10,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/Posters/9df3a1ba153b3a14d3eca296bca7ba35.jpg?v=00002177",
                            Synopsis = "Mia (Sophie Wilde) ha pasado años evitando el trauma de la muerte de su madre. Esto cambiará cuando sus amigos descubran cómo conjurar espíritus usando una mano embalsamada.¿En los muertos o los vivos?",
                            Title = "Hablame",
                            Trailer = "https://www.youtube.com/watch?v=ZYASq2O1qt0&ab_channel=DiamondFilmsLatam"
                        },
                        new
                        {
                            Id = 5,
                            Genre = 1,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/ComingSoon/200x285/964.jpg?v=00002177",
                            Synopsis = "la película es la historia de un adolescente que juega a Gran Turismo y que, gracias a su habilidad con los videojuegos, gana una serie de concursos de Nissan para convertirse en piloto de carreras profesional.",
                            Title = "Gran turismo",
                            Trailer = "https://www.youtube.com/watch?v=VF1Aq8KrQO4&ab_channel=SonyPicturesArgentina"
                        },
                        new
                        {
                            Id = 6,
                            Genre = 3,
                            PosterUrl = "https://th.bing.com/th/id/OIP.NNDzj9c4s1ntnvDOwTDNagHaLH?w=115&h=180&c=7&r=0&o=5&pid=1.7",
                            Synopsis = "La trama sigue a Jake Sully, un ex-marine enviado a Pandora, donde se encuentra con los Na'vi, una raza alienígena.",
                            Title = "Avatar",
                            Trailer = "https://www.youtube.com/watch?v=AZS_d_hS2dM&ab_channel=20thCenturyStudiosEspa%C3%B1a"
                        },
                        new
                        {
                            Id = 7,
                            Genre = 7,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/Posters/6aa4601e49a56d928205c271b55fd463.jpg?v=00002177",
                            Synopsis = "Disney. City, donde conviven los habitantes del fuego, el agua, la tierra y el aire. La historia nos presenta a Ember, una joven dura, ingeniosa y feroz, cuya amistad con un chico divertido y que se deja llevar por la corriente.",
                            Title = "Elementos",
                            Trailer = "https://www.youtube.com/watch?v=TGZQqHi7lrc&ab_channel=DisneyStudiosLA"
                        },
                        new
                        {
                            Id = 8,
                            Genre = 6,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/Posters/96dd838f4e7b4622c92b79f792a169be.jpg?v=00002177",
                            Synopsis = "Irina, una oficial de policía, regresa a la Patagonia. Sin embargo, el asesinato de la hija de una vieja amiga la lleva a involucrarse en un caso que parece ser ignorado.",
                            Title = "Fragmentada",
                            Trailer = "https://www.youtube.com/watch?v=1vqyfkFMkos&ab_channel=PensilvaniaFilms"
                        },
                        new
                        {
                            Id = 9,
                            Genre = 1,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/Posters/b47eae0ffae291cbcbba298ab89c1545.jpg?v=00002177",
                            Synopsis = "Jaime Reyes, mientras busca encontrar su propósito en el mundo, el destino interviene cuando Jaime inesperadamente se encuentra en posesión de una antigua reliquia de biotecnología alienígena: el Escarabajo, cambiando para siempre su destino.",
                            Title = "Blue Beetle",
                            Trailer = "https://www.youtube.com/watch?v=Shmvk5M-NV8&ab_channel=WarnerBros.PicturesLatinoam%C3%A9rica"
                        },
                        new
                        {
                            Id = 10,
                            Genre = 4,
                            PosterUrl = "https://www.originalfilmart.com/cdn/shop/files/scarymovie_2000_original_film_art.webp?v=1683910671",
                            Synopsis = "Una parodia de los filmes de asesinatos donde un homicida vengativo acecha a un grupo de adolescentes.",
                            Title = "Scary Movie",
                            Trailer = "https://www.youtube.com/watch?v=HTLPULt0eJ4&ab_channel=Miramax"
                        },
                        new
                        {
                            Id = 11,
                            Genre = 2,
                            PosterUrl = "https://th.bing.com/th/id/OIP.8RmTep5x66mXiB7HiOqUUgHaLg?w=116&h=180&c=7&r=0&o=5&pid=1.7",
                            Synopsis = "En la era Sengoku, durante el conflicto de los Estados, un ronin conocido como Nanashi (que significa \"sin nombre\") rescata a un niño llamado Kotarou y su leal perro Tobimaru en un templo desolado. ",
                            Title = "The sword of the stranger",
                            Trailer = "https://www.youtube.com/watch?v=dYGpmgxKpNs&ab_channel=RainHNg"
                        },
                        new
                        {
                            Id = 12,
                            Genre = 8,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/Posters/354c9bfec5030e674afdbe739711567e.jpg?v=00002177",
                            Synopsis = "Tras su arrolladora carrera como miembro de uno de los grupos de K-pop más populares de Corea, ha decidido emprender su propio camino. Con el lanzamiento de su primer álbum de estudio.",
                            Title = "Kang daniel my parade",
                            Trailer = "https://www.youtube.com/watch?v=OHMGeuaG_54&ab_channel=KinoHeliosPolska"
                        },
                        new
                        {
                            Id = 13,
                            Genre = 1,
                            PosterUrl = "https://img.goodfon.ru/wallpaper/original/1/6f/batman-begins-the-dark-knight-4126.jpg",
                            Synopsis = "Batman tiene que mantener el equilibrio entre el heroísmo y el vigilantismo para pelear contra un vil criminal conocido como el Guasón, que pretende sumir Ciudad Gótica en la anarquía.",
                            Title = "Batman: el caballero de la noche",
                            Trailer = "https://www.youtube.com/watch?v=TQfATDZY5Y4&ab_channel=Legendary"
                        },
                        new
                        {
                            Id = 14,
                            Genre = 3,
                            PosterUrl = "https://www.lahiguera.net/cinemania/pelicula/6388/guardianes_de_la_galaxia-cartel-5615.jpg",
                            Synopsis = "Un aventurero espacial se convierte en la presa de unos cazadores de tesoros después de robar el orbe de un villano traicionero. Cuando descubre su poder, debe hallar la forma de unir a unos rivales para salvar al universo.",
                            Title = "Guardianes de la Galaxia",
                            Trailer = "https://www.youtube.com/watch?v=qdIuXCfUKM8&ab_channel=MarvelLatinoam%C3%A9ricaOficial"
                        },
                        new
                        {
                            Id = 15,
                            Genre = 6,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/Posters/012951356fdd8d9145a7c28c1d72e48e.jpg?v=00002177",
                            Synopsis = "En la Irlanda rural de 1981, Cáit, una niña de nueve años, vive retraída entre su familia numerosa. Sus padres la envían a casa de unos parientes. Allí, la pequeña se hará eco del secreto que esta familia adoptiva.",
                            Title = "The quiet girl",
                            Trailer = "https://youtu.be/S9ExUXUIGEY"
                        },
                        new
                        {
                            Id = 16,
                            Genre = 1,
                            PosterUrl = "https://th.bing.com/th/id/OIP.e8BVI2EbDHPGc8b7-UUqLAHaJQ?w=178&h=223&c=7&r=0&o=5&pid=1.7",
                            Synopsis = "Dos hermanos plomeros, Mario y Luigi, caen por las alcantarillas y llegan a un mundo subterráneo mágico en el que deben enfrentarse al malvado Bowser para rescatar a la princesa Peach, quien ha sido forzada a aceptar casarse con él.",
                            Title = "Mario Bros",
                            Trailer = "https://www.youtube.com/watch?v=S9ExUXUIGEY&ab_channel=zetafilmstrailerszeta"
                        },
                        new
                        {
                            Id = 17,
                            Genre = 4,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/Posters/6546c70272a606d297ad53bfb9162189.jpg?v=00002177",
                            Synopsis = "Exéntrica e individualista, Barbie, una muñeca que vive en 'Barbieland' es expulsada al mundo real por no ser lo suficientemente perfecta.",
                            Title = "Barbie",
                            Trailer = "https://www.youtube.com/watch?v=eUP3hlBel5I&ab_channel=WarnerBros.PicturesLatinoam%C3%A9rica"
                        },
                        new
                        {
                            Id = 18,
                            Genre = 1,
                            PosterUrl = "https://static.cinemarkhoyts.com.ar/Images/ComingSoon/200x285/983.jpg?v=00002177",
                            Synopsis = "Tom Harris (Gerard Butler) un agente encubierto de la CIA que trabaja en Oriente Medio se verá en peligro a causa de la filtración de su misión encubierta que revelará su verdadera identidad. Atrapado en pleno territorio enemigo.",
                            Title = "Escape bajo fuego",
                            Trailer = "https://www.youtube.com/watch?v=pJMW_S7jPGc&ab_channel=DiamondFilmsLatam"
                        },
                        new
                        {
                            Id = 19,
                            Genre = 2,
                            PosterUrl = "https://m.media-amazon.com/images/I/811IcpNS05L.jpg",
                            Synopsis = "De camino al prestigiado campeonato Copa Pistón, un automóvil de carreras que sólo se preocupa por ganar aprende sobre lo que realmente es importante en la vida de varios vehículos que viven en un pueblo a lo largo de la histórica Ruta 66.",
                            Title = "Cars",
                            Trailer = "https://www.youtube.com/watch?v=SbXIj2T-_uk&ab_channel=nickbtube"
                        },
                        new
                        {
                            Id = 20,
                            Genre = 4,
                            PosterUrl = "https://cinenacional.com/wp-content/uploads/2023/07/julio-felices-por-siempre-afiche.jpg",
                            Synopsis = "Julio es de la generación criada por padres divorciados, tuvo relaciones amorosas que lo desilusionaron: Blanca lo traicionó y Florencia lo aburrió. Pero todo cambia cuando conoce a Claire, se enamoran profundamente.",
                            Title = "Julio felices por siempre",
                            Trailer = "https://www.youtube.com/watch?v=jc2vGui9Hqo&ab_channel=Regi%C3%B3nCinema"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Screen", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SalaId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Capacidad");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("Id");

                    b.ToTable("Salas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 5,
                            Name = "Sala A"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 15,
                            Name = "Sala B"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 35,
                            Name = "Sala C"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Show", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FuncionId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE")
                        .HasColumnName("Fecha");

                    b.Property<int>("MovieId")
                        .HasColumnType("int")
                        .HasColumnName("PeliculaId");

                    b.Property<TimeSpan>("Schedule")
                        .HasColumnType("time")
                        .HasColumnName("Horario");

                    b.Property<int>("ScreenId")
                        .HasColumnType("int")
                        .HasColumnName("SalaId");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("ScreenId");

                    b.ToTable("Funciones", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ShowId")
                        .HasColumnType("int")
                        .HasColumnName("FuncionId");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Usuario");

                    b.HasKey("TicketId", "ShowId");

                    b.HasIndex("ShowId");

                    b.ToTable("Tickets", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.HasOne("Domain.Entities.Genre", "GenreNav")
                        .WithMany()
                        .HasForeignKey("Genre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenreNav");
                });

            modelBuilder.Entity("Domain.Entities.Show", b =>
                {
                    b.HasOne("Domain.Entities.Movie", "MovieNav")
                        .WithMany("Shows")
                        .HasForeignKey("MovieId");

                    b.HasOne("Domain.Entities.Screen", "ScreenNav")
                        .WithMany()
                        .HasForeignKey("ScreenId");

                    b.Navigation("MovieNav");

                    b.Navigation("ScreenNav");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Show", "ShowNav")
                        .WithMany("Tickets")
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShowNav");
                });

            modelBuilder.Entity("Domain.Entities.Movie", b =>
                {
                    b.Navigation("Shows");
                });

            modelBuilder.Entity("Domain.Entities.Show", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
